# Generated by Django 3.2 on 2022-01-18 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата запроса к геокодеру'),
        ),
    ]
