# Generated by Django 3.2 on 2022-01-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0004_alter_coordinate_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinate',
            name='status',
        ),
        migrations.AddField(
            model_name='coordinate',
            name='are_defined',
            field=models.BooleanField(default=False, verbose_name='статус координат'),
        ),
    ]
