# Generated by Django 3.2 on 2022-01-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0005_auto_20220122_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='are_defined',
            field=models.BooleanField(default=False, verbose_name='координаты определены'),
        ),
    ]
